default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_todo_app

production:
  <<: *default
  database: my_todo_app_production
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>